### ISSUE TITLE
Update results in "no data to commit"

### ISSUE THREAD

**Issue by JohnEPierce** [rbcavanaugh/aphasia-tech-map#8]
Running 'rebuild website' is successful but in 'render Rmarkdown files and commit results' it reports no changes to commit. The data is not updated with changes made to google sheets since Oct 21.
When I run getData.R locally it results in updated data. 
Any ideas?

**Comment by rbcavanaugh** [comment]
Hmm. Where are you running rebuild website? In theory the GitHub actions should take care of the rebuild on any commit and every Monday. 

You can test it by opening any r script, adding a comment or space, and committing the result on the GitHub.com page (so not locally) and the whole thing should rebuild in 10 minutes or so. 

If we're still getting an error after that, there's a problem and I need to look closer.

**Comment by JohnEPierce** [comment]
That could explain it - on Friday I altered the google spreadsheet link which caused it to rebuild. Today I manually told it to rebuild by going to actions and hitting re-run but perhaps that doesn't do what I think it does.
Anyway it has now updated correctly, probably because it was scheduled ¯\_(ツ)_/¯
